name: Build manylinux with dependencies and deploy images to GitHub Packages
on: [push] # todo
jobs:
  build_push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        manylinux_tag: [
          "manylinux2014_x86_64",
#          "manylinux2014_i686",
#          "manylinux2014_aarch64",
#          "manylinux2014_ppc64le",
#          "manylinux2014_s390x"
        ]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Prepare registry name
        run: echo IMAGE_REPOSITORY=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
      - name: ${{ matrix.manylinux_tag }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: build/manylinux/Dockerfile
          push: true
          build-args: MANYLINUX_PLATFORM=${{ matrix.manylinux_tag }}
          tags: ${{ env.IMAGE_REPOSITORY }}/tgcalls/${{ matrix.manylinux_tag }}:latest
