name: Build and publish wheels for Linux and many Python versions
on:
  push:
    paths:
      - '.github/workflows/build_and_publish_python_wheels_for_many_versions.yaml'
      - 'build/manylinux/entrypoint.sh'
      - 'action.yml'
      - 'setup.py'
      - 'CMakeLists.txt'
      - 'tgcalls/**'
jobs:
  build_wheels_for_linux:
    name: Build and publish wheels for Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        manylinux_tag: [
            'manylinux2014_x86_64',
            'manylinux2014_aarch64',
        ]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build for ${{ matrix.manylinux_tag }}
        uses: ./
        with:
          image: build/manylinux/${{ matrix.manylinux_tag }}.Dockerfile
          python-versions: 'cp36-cp36m cp37-cp37m cp38-cp38 cp39-cp39'
          manulinux-platform: ${{ matrix.manylinux_tag }}
          twine-username: ${{ secrets.PYPI_USERNAME }}
          twine-password: ${{ secrets.PYPI_PASSWORD }}
