name: Build and publish wheels for Linux and many Python versions
on:
  push:
    paths:
      - '.github/workflows/build_and_publish_python_wheels_for_many_versions.yaml'
      - 'build/manylinux/entrypoint.sh'
      - 'action.yml'
      - 'setup.py'
      - 'CMakeLists.txt'
      - 'tgcalls/**'
jobs:
  build_wheels_for_linux:
    name: Build and publish wheels for Linux
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
#      - name: Build for x86_64
#        uses: ./build/manylinux/manylinux2014_x86_64
#        with:
#          python-versions: 'cp36-cp36m cp37-cp37m cp38-cp38 cp39-cp39'
#          manulinux-platform: manylinux2014_x86_64
#          twine-username: ${{ secrets.PYPI_USERNAME }}
#          twine-password: ${{ secrets.PYPI_PASSWORD }}
      - name: Build for aarch64
#        with:
#          python-versions: 'cp36-cp36m cp37-cp37m cp38-cp38 cp39-cp39'
#          manulinux-platform: manylinux2014_aarch64
#          twine-username: ${{ secrets.PYPI_USERNAME }}
#          twine-password: ${{ secrets.PYPI_PASSWORD }}
        run: |
            # Enable docker daemon support for --platform parameter
            echo '{"experimental": true}' | sudo tee /etc/docker/daemon.json > /dev/null
            sudo systemctl restart docker

            # Configure qemu-user-static
            docker run --rm --tty \
              --security-opt apparmor:unconfined \
              --cap-add SYS_ADMIN \
              multiarch/qemu-user-static --reset -p yes

            docker run --rm \
              --security-opt apparmor:unconfined \
              --cap-add SYS_ADMIN \
              --device /dev/fuse \
              --volume /sys \
              --volume /sys/fs/cgroup:/sys/fs/cgroup:ro \
              --volume $GITHUB_WORKSPACE:/github/workspace \
              --workdir $GITHUB_WORKSPACE \
              --platform "linux/arm64" \
              ghcr.io/marshalx/tgcalls/manylinux2014_aarch64-webrtc-entrypoint:latest \
              "cp36-cp36m cp37-cp37m cp38-cp38 cp39-cp39" \
              "manylinux2014_aarch64" \
              ${{ secrets.PYPI_USERNAME }} \
              ${{ secrets.PYPI_PASSWORD }} \


