on: [push]

jobs:
  buil:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Build
        uses: ./build/linux